on:
  pull_request:
    types:
      - labeled
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Say Something
        run: echo Hello
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Check for patch
        if: ${{ github.event.label.name == 'patch' }}
        run: |
          git status
          git add .
          git commit -m "commit from github runner"
          ./gradlew release -Prelease.versionIncrementer=incrementPatch
          git --config --global user.name "Lazare-Ge"
          git --config --global user.email "lazare.giorgobiani.lg@gmail.com
          git push --tags
      - name: Check for minor
        if: ${{ github.event.label.name == 'minor' }}
        run: echo This is minor label
      - name: Check for major
        if: ${{ github.event.label.name == 'major' }}
        run: echo This is major label

