on:
  pull_request:
    types:
      - labeled
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Say Something
        run: echo Hello
      - name: Check label messsage
        run: echo ${{ github.event.label.name }}

